In [5]:
%load_ext autoreload
%autoreload 2
import pandas as pd
from src import analyzer
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from tqdm import tqdm_notebook as tqdm
from sklearn.preprocessing import LabelEncoder
import seaborn as sns

In [3]:
lista_k = range(2, 20)
lista_experimentos = np.arange(0,1)
le = LabelEncoder()
for i in lista_experimentos:
    exp = i+1
    print('--------- agrupamentos do experimento '+ str(exp)+' ---------')
    dir_experimento = 'experimento_'+str(exp)
    df = pd.read_csv('dados/'+dir_experimento+'/vetores_teste.csv')

    for modelo in df.iloc[:,3:]:
        print('agrupando vetores gerados pelo modelo '+modelo)
        df[modelo] = df[modelo].apply(lambda x: analyzer.converter_string_array(x).reshape(-1))
        X = np.stack(df[modelo])
        y = df['assunto']
        le.fit(y)
        y = le.transform(y)

        lista_scores_k = analyzer.computar_scores_agrupamento(X, y, dir_experimento, modelo, lista_k)
        analyzer.gerar_graficos_kmeans(lista_scores_k, dir_experimento, modelo)

--------- agrupamentos do experimento 1 ---------
agrupando vetores gerados pelo modelo vec_w2v_ger_soma



agrupando vetores gerados pelo modelo vec_ftt_ger_soma



agrupando vetores gerados pelo modelo vec_glv_ger_soma



agrupando vetores gerados pelo modelo vec_w2v_jur_soma



agrupando vetores gerados pelo modelo vec_ftt_jur_soma



agrupando vetores gerados pelo modelo vec_glv_jur_soma



agrupando vetores gerados pelo modelo doc2vec_jur


In [3]:
import numpy as np
arrays = [np.random.randn(3, 4) for _ in range(10)]
arrays

[array([[-1.75337559, -1.37420784, -1.85380514, -0.2483768 ],
        [ 1.58627154,  1.63047037,  0.27436612,  1.74448475],
        [ 0.14963845,  1.39846274,  0.97595348,  0.49302216]]),
 array([[-0.54832643,  1.95269766, -0.77442282,  0.96836788],
        [ 0.41381138, -0.52557561,  0.14372263, -1.39850914],
        [-0.22425534,  0.3495785 , -0.40275713,  0.38131942]]),
 array([[ 0.32950958,  1.73482668,  0.37695322,  1.49951611],
        [ 0.2979788 ,  0.34682243,  0.27531613,  1.67223478],
        [-0.42088268,  0.32011149,  1.00762807,  0.43223204]]),
 array([[ 0.15774154,  0.81600037, -1.81531063,  0.93656625],
        [ 0.71327102, -1.13530628,  0.2524412 ,  0.28457662],
        [ 0.4501278 , -0.82184863,  0.18448236, -1.01363359]]),
 array([[-0.46818736,  0.29599649,  0.02163768, -0.21838599],
        [ 0.54320704,  0.53628504,  0.95016793, -0.77760301],
        [ 0.00391397,  0.39549368, -1.63534492,  0.53434401]]),
 array([[ 0.25605156,  0.70728728, -0.14525677, -0.16282297]

In [7]:
plt.rcParams.update(plt.rcParamsDefault)